# docker-compose.override.yml
version: '3.8'
services:
  kong:
    environment:
      - KONG_PROXY_LISTEN=0.0.0.0:8000
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_TRUSTED_IPS=0.0.0.0/0,::/0
      - KONG_REAL_IP_HEADER=X-Forwarded-For
      - KONG_REAL_IP_RECURSIVE=on
    ports:
      - "0.0.0.0:54321:8000"  # API Gateway - binds to all interfaces
      - "0.0.0.0:54322:8443"
  db:
    ports:
      - "0.0.0.0:54322:5432"   # PostgreSQL
  studio:
    ports:
      - "0.0.0.0:54323:3000"  # Studio
  inbucket:
    ports:
      - "0.0.0.0:54324:9000"  # Email testing