version: '3.8'

services:
  vite-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./index.html:/app/index.html
      - ./.env.local:/app/.env.local
      - /app/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
